export const DISCOUNT = {
  PERCENT: 'PERCENT',
  FIXED: 'FIXED'
}

export const STAY = {
  ROOM: 'ROOM',
  TTC: 'TTC'
}

export const SEASON = {
  SUMMER_2015: 'SUMMER_2015',
  WINTER_2016: 'WINTER_2016',
  SUMMER_2016: 'SUMMER_2016',
  WINTER_2017: 'WINTER_2017',
  SUMMER_2017: 'SUMMER_2017',
  WINTER_2018: 'WINTER_2018',
  SUMMER_2018: 'SUMMER_2018'
}

export const ROOM_ID = {
  BEACHFRONT: 'BEACHFRONT',
  BEACHFRONT_SHARING: 'BEACHFRONT_SHARING',
  OCEAN_VIEW: 'OCEANVIEW',
  OCEAN_VIEW_SHARING: 'OCEANVIEW_SHARING',
  BEACH_HUT: 'BEACH_HUT',
  BEACH_HUT_SHARING: 'BEACH_HUT_SHARING',
  GARDEN_BATH: 'GARDEN_BATH',
  GARDEN_BATH_SHARING: 'GARDEN_BATH_SHARING',
  GARDEN_DOUBLE: 'GARDEN_DOUBLE',
  GARDEN_DOUBLE_SHARING: 'GARDEN_DOUBLE_SHARING',
  GARDEN_SINGLE: 'GARDEN_SINGLE',
  GARDEN_SHARED: 'GARDEN_SHARED',
  GARDEN_SHARED_SHARING: 'GARDEN_SHARED_SHARING',
  DORMITORY: 'DORMITORY',
  TENT_HUT: 'TENT_HUT',
  TENT_SPACE: 'TENT_SPACE',
  NULL_ROOM: 'NULL_ROOM'
}
